package ml.kalanblowSystemManagement.dto.response;

public enum Status {

	Ok, BAD_REQUEST, UNAUTHORIZED, VALIDATION_EXCEPTION, EXCEPTION, WRONG_CREDENTIALS, ACCESS_DENIED, NOT_FOUND,
	DUPLICATE_ENTITY;
}
